name: Patch and Upload

on:
  workflow_dispatch:

jobs:
  fetch-and-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute patching script
        run: |
          chmod +x patch.sh
          ./patch.sh

      - name: Create Release
        run: |
          gh release create v${{ env.INFINITY_VERSION }} \
            --title "Re-Infinity-${{ env.INFINITY_VERSION }}" \
            --notes "Release notes for Re-Infinity version ${{ env.INFINITY_VERSION }}" \
            --repo ${{ github.repository }} \
            --draft false \
            --prerelease false

      - name: Upload Release Asset
        run: |
          gh release upload v${{ env.INFINITY_VERSION }} Re-Infinity-${{ env.INFINITY_VERSION }}.apk \
            --repo ${{ github.repository }}
